openapi: 3.0.0
info:
  description: API CebuloBoya
  version: 0.0.1
  title: CebulaPi
  contact:
    email: mlegiecki@gmail.com
    name: Mateusz Legięcki
servers:
  - url: 'https://cebul.ga'
paths:
  /last_promotions:
    get:
      summary: A list of most recent promotions in all shops
      operationId: getLastPromotions
      responses:
        '200':
          description: Shop entry with most recent promotions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shop'
components:
  schemas:
    Shop:
      type: object
      properties:
        name:
          type: string
        last_promotions:
          type: array
          items:
            $ref: '#/components/schemas/Promotion'
    Promotion:
      type: object
      properties:
        product_name:
          type: string
        old_price:
          type: number
          format: float
          minimum: 0
        new_price:
          type: number
          format: float
          minimum: 0
        url:
          type: string
          format: url
        code:
          type: string
          nullable: true
