openapi: 3.0.0
info:
  description: API CebuloBoya
  version: 0.0.1
  title: CebulaPi
  contact:
    email: mlegiecki@gmail.com
    name: Mateusz Legięcki
servers:
  - url: 'https://cebul.ga'
paths:
  /last_promotions:
    get:
      summary: A list of most recent promotions in all shops
      operationId: getLastPromotions
      parameters:
      - $ref: '#/components/parameters/limit'
      responses:
        '200':
          description: Shop entry with most recent promotions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shop'
  /rss:
    get:
      summary: RSS feed
      operationId: getRssFeed
      parameters:
      - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: Generated feed
  /saved_money:
    get:
      summary: Saved money info
      operationId: getSavedMoney
      responses:
        '200':
          description: Saved money report
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    format: foat
                  shops:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          format: integer
                        name:
                          type: string
                        saved_money:
                          type: number
                          format: float

components:
  parameters:
    limit:
      in: query
      name: limit
      schema:
        type: integer
        maximum: 20
        minimum: 0
  schemas:
    Shop:
      type: object
      properties:
        id:
          type: number
          format: integer
        name:
          type: string
        last_promotions:
          type: array
          items:
            $ref: '#/components/schemas/Promotion'
    Promotion:
      type: object
      properties:
        product_name:
          type: string
        old_price:
          type: number
          format: float
          minimum: 0
        new_price:
          type: number
          format: float
          minimum: 0
        url:
          type: string
          format: url
        code:
          type: string
          nullable: true
        timestamp:
          type: number
          format: long
