version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-ci.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-


      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-ci.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-ci.txt" }}

      - run:
          name: run static analisis
          command: |
            export PYTHONPATH=${PYTHONPATH}:~/repo/cebulobot/bot
            . venv/bin/activate
            flake8
      - run:
          name: run tests
          command: |
            export PYTHONPATH=${PYTHONPATH}:~/repo/cebulobot/bot
            cp sample_config.py config.py
            . venv/bin/activate
            pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports
